name: Deploy Storybook as Static Site

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install
      - run: yarn run build-storybook
      - run: yarn run deploy-storybook
