name: Docs Test

on:
  push:
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_vocabulary:
    name: Check Vocabulary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check Vocabulary
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install
      - run: yarn run test-docs
