name: Publish

on: [push]

jobs:
  publish:
   name: Publish
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
       token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
       fetch-depth: 0
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
       node-version: 18
    - name: Inject NPM_TOKEN
      run: |
        echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile && yarn run bootstrap
    - name: Build
      run: |
        yarn run build
    - name: Publish
      run: |
        npx lerna publish from-package --yes
