name: Publish

on:
  push:
    branches:
      - main
      - develop

jobs:
  publish:
    if: github.event.pull_request.merged == true
    environment: Production
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Inject NPM_TOKEN
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile && yarn run bootstrap
      - name: Build
        run: |
          yarn run build
      - name: Version and Publish
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --yes
          fi

          npx lerna publish from-package --yes --force-publish
      - name: Build Storybook as Static Site
        run: |
          yarn run build-storybook

      - name: Deploy Storybook
        run: |
          yarn run deploy-storybook
