name: Publish

on: [push]

jobs:
  publish:
   name: Publish
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
       token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
       fetch-depth: 0
    - name: Build
      uses: actions/setup-node@v3
      with:
       node-version: 18
    - run: ${{ secrets.NPM_TOKEN }} > .npmrc
    - run: yarn install --frozen-lockfile
    - run: yarn run bootstrap
    - run: yarn run build
    - run: npx lerna publish
